server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: sidiflow-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
error:
  resource:
    not-found: Registro no encontrado.
    already-exists: El registro ya existe.
  username:
    not-found: Datos incorrectos.
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: sidiflow-api
      audience: ${JWT_AUDIENCE:sidiflow-api}
      expiration-minutes: 15