-- ==================================================
-- Script de creación de base de datos
-- PostgreSQL
-- Softidi
-- ==================================================

-- ==================================================
-- Table currency
-- ==================================================

CREATE TABLE currency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(3) NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_currency PRIMARY KEY (id),
    CONSTRAINT uk_currency_code UNIQUE (code),
    CONSTRAINT chk_currency_code_format CHECK (code ~ '^[A-Z]{3}$')
);

COMMENT ON COLUMN currency.code IS 'Código ISO 4217 de la moneda';

-- ==================================================
-- Table app_user
-- ==================================================

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(150) NOT NULL,
    first_name VARCHAR(150),
    last_name VARCHAR(150),
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    default_currency_id BIGINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT fk_app_user_currency FOREIGN KEY (default_currency_id) REFERENCES currency(id)
);

CREATE UNIQUE INDEX uk_app_user_username ON app_user (LOWER(username));
CREATE UNIQUE INDEX uk_app_user_email ON app_user (LOWER(email));

COMMENT ON COLUMN app_user.status IS 'Estado del usuario: 0=Bloqueado, 1=Activo, 2=Inactivo';

-- ==================================================
-- Table app_role
-- ==================================================
CREATE TABLE app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_role PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_app_role_name ON app_role (LOWER(name));

-- ==================================================
-- Table app_user_role
-- ==================================================
CREATE TABLE app_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by BIGINT,
    CONSTRAINT pk_app_user_role PRIMARY KEY (id),
    CONSTRAINT uk_app_user_role_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_app_user_role_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_app_user_role_role FOREIGN KEY (role_id) REFERENCES app_role(id),
    CONSTRAINT fk_app_user_role_assigned_by FOREIGN KEY (assigned_by) REFERENCES app_user(id)
);

CREATE INDEX ix_app_user_role_role ON app_user_role (role_id);

-- ==================================================
-- Table category
-- ==================================================

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    type SMALLINT NOT NULL,
    user_id BIGINT,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT chk_category_type CHECK (type IN (1, 2)),
    CONSTRAINT fk_category_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_category_created_by FOREIGN KEY (created_by) REFERENCES app_user(id),
    CONSTRAINT fk_category_updated_by FOREIGN KEY (updated_by) REFERENCES app_user(id)
);

CREATE UNIQUE INDEX uk_category_global_name_type ON category (LOWER(name), type) WHERE user_id IS NULL;
CREATE UNIQUE INDEX uk_category_user_name_type ON category (user_id, LOWER(name), type) WHERE user_id IS NOT NULL;

COMMENT ON TABLE category IS 'Categorías (comida, transporte, etc.)';
COMMENT ON COLUMN category.user_id IS 'Usuario propietario de la categoría; NULL indica una categoría global';
COMMENT ON COLUMN category.type IS 'Tipo de categoría: 1=Ingreso, 2=Gasto';

-- ==================================================
-- Table payment_method
-- ==================================================

CREATE TABLE payment_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    type SMALLINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payment_method PRIMARY KEY (id),
    CONSTRAINT fk_payment_method_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT chk_payment_method_type CHECK (type IN (1, 2 ,3 ,4, 5))
);

COMMENT ON COLUMN payment_method.type IS 'Tipo de método de pago: 1=Efectivo, 2=Tarjeta débito, 3=Tarjeta crédito, 4=Transferencia, 5=Otro';

CREATE UNIQUE INDEX uk_payment_method_user_name ON payment_method (user_id, LOWER(name));

-- ==================================================
-- Table financial_transaction
-- ==================================================

CREATE TABLE financial_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    user_id BIGINT NOT NULL,
    currency_id BIGINT NOT NULL,
    payment_method_id BIGINT,
    category_id BIGINT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    transaction_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    CONSTRAINT pk_financial_transaction PRIMARY KEY (id),
    CONSTRAINT chk_financial_transaction_amount_positive CHECK (amount > 0),
    CONSTRAINT fk_financial_transaction_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_financial_transaction_currency FOREIGN KEY (currency_id) REFERENCES currency(id),
    CONSTRAINT fk_financial_transaction_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method(id),
    CONSTRAINT fk_financial_transaction_category FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT fk_financial_transaction_created_by FOREIGN KEY (created_by) REFERENCES app_user(id),
    CONSTRAINT fk_financial_transaction_updated_by FOREIGN KEY (updated_by) REFERENCES app_user(id)
);

CREATE INDEX ix_financial_transaction_user_transaction_at ON financial_transaction (user_id, transaction_at DESC);
CREATE INDEX ix_financial_transaction_category ON financial_transaction (category_id);
CREATE INDEX ix_financial_transaction_payment_method ON financial_transaction (payment_method_id);
CREATE INDEX ix_financial_transaction_currency ON financial_transaction (currency_id);

COMMENT ON TABLE financial_transaction IS 'Tabla que registra todas las transacciones financieras del usuario';
COMMENT ON COLUMN financial_transaction.category_id IS 'Categoría asociada a la transacción; la categoría determina si corresponde a un ingreso o gasto';
